<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangaysSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barangays = [
            ['barangay_name' => 'BRGY13-B (POB)', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 14-B (POB)', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 15-B (POB)', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 21-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 22-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 23-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 24-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 25-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 26-C (POB)', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 27-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 28-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 29-C (POB)', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 30-C', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 31-D', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 32-D', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY CENTRO AGDAO/ SAN JUAN', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY AGDAO PROPER', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LEON GARCIA', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY LAPU-LAPU', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY GOVERNOR VICENTE DUTERTE', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY TOMAS MONTEVERDE', 'station_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BIAO JOAQUIN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CALINAN POB', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CAWAYAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DACUDAO', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DALAGDAG', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DOMINGA', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'INAYANGAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LACSON', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LAMANAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LAMPIANAO', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MEGCAWAYAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PANGYAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'RIVERSIDE', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SALOY', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SIRIB', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SUBASTA', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TALOMO RIVER', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAMAYONG', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'WANGAN', 'station_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAGUIO (POB)', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CADALIAN', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CARMEN', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'GUMALANG', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MALAGOS', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAMBOBONG', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAWAN-TAWAN', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'WINES', 'station_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAGANIHAN', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BANTOL', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BUDA', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DALAG LUMOT', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DATU SALUMAY', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'GUMITAN', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MAGSAYSAY', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MARILOG', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MALAMBA', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SALAYSAY', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SUAWAN (TULI)', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAMUGAN', 'station_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ACACIA', 'station_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CALLAWA', 'station_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'INDANGAN', 'station_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MANDUG', 'station_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'WAAN', 'station_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '74-A MATINA CROSSING', 'station_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '76-A SIR', 'station_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '75-A MATINA APLAYA', 'station_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LANGUB', 'station_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MA-A', 'station_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MAGTUOD', 'station_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'NEW CARMEN', 'station_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAGO APLAYA', 'station_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAGO GALLERA', 'station_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BALIOK', 'station_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CATALUNAN PEQUENO', 'station_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DUMOY', 'station_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '16-B (POB)', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '17-B (POB)', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '18-B', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => '20-B', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PACIANO BANGOY', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'RAFAEL CASTILLO', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SAN ANTONIO', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'UBALDE', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'WILFREDO AQUINO', 'station_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ATAN-AWE', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BARACATAN', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAYABAS', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CATIGAN', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'EDEN', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'KILATE', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SIBULAN', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAGURANO', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TIBULOY', 'station_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 1-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 2-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 3-A (POB)', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 4-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 5-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 6-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 7-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 8-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 9-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 10-A', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 11-B (POB)', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 12-B', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 19-B', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 33-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 34-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 35-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 36-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 37-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 38-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 39-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BRGY 40-D', 'station_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ANGALAN', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BALENGAENG', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BIAO ESCUELA', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BIAO GUIANGA', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LOS AMIGOS', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MANUEL GUIANGA', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'NEW VALENCIA', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAGAKPAN', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TALANDANG', 'station_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CATALUNAN GRANDE', 'station_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MATINA PANGI', 'station_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TALOMO', 'station_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ANGLIONGTO', 'station_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PAMPANGA', 'station_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PANACAN', 'station_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SASA', 'station_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'VICENTE HIZON SR', 'station_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BUHANGIN', 'station_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CABANTIAN', 'station_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'COMMUNAL', 'station_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TIGATTO', 'station_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BUNAWAN', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'GATUNGAN', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ILANG', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LASANG', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MAHAYAG', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MUDIANG', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SAN ISIDRO', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TIBUNGCO', 'station_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'COLOSAS', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'FATIMA (BENOWANG)', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LUMIAD', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MABUHAY', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MALABOG', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MAPULA', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PARADISE EMBAK', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PANALUM', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PANDAITAN', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'PAQUIBATO (POB)', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SALAPAWAN', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SUMIMAO', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAPAK', 'station_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ALAMBRE', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BANGKAS HEIGHTS', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BATO', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BINUGAO', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CAMANSI', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'CROSSING BAYABAS', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DALIAO', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'DALIAON PLANTATION', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LIZADA', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'LUBOGAN', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MARAPANGI', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MULIG', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'SIRAWAN', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TAGLUNO', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TORIL POBLACION', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TUNGAKALAN', 'station_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'BAGO OSHIRO', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MANAMBULAN', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MATINA BIAO', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'MINTAL', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'STO NINO', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TACUNAN', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'TUGBOK', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['barangay_name' => 'ULA', 'station_id' => 9, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('barangays')->insert($barangays);
    }
}
